# Generated by Django 6.0.4 on 2026-06-25 05:46

import django.db.models.deletion
import loan_agreements.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lender_name', models.CharField(default='LoanSphere Financial Ltd.', max_length=180)),
                ('status', models.CharField(choices=[('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed')], default='awaiting_signature', max_length=30)),
                ('signature_image', models.FileField(blank=True, null=True, upload_to=loan_agreements.models.agreement_upload_path)),
                ('signature_text', models.CharField(blank=True, max_length=180, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to=loan_agreements.models.agreement_upload_path)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True, null=True)),
                ('co_applicant_status', models.CharField(choices=[('none', 'None'), ('invited', 'Invited'), ('skipped', 'Skipped'), ('accepted', 'Accepted')], default='none', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loan_applications.loanapplication')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoApplicantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('invite_link', models.URLField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_applicant_invitations', to='loan_agreements.loanagreement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
