# Generated by Django 6.0.4 on 2026-06-25 04:39

import django.db.models.deletion
import kyc_verification.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('driving_license', 'Driving License'), ('passport', 'Passport')], max_length=40, null=True)),
                ('id_front_image', models.FileField(blank=True, null=True, upload_to=kyc_verification.models.kyc_upload_path)),
                ('id_back_image', models.FileField(blank=True, null=True, upload_to=kyc_verification.models.kyc_upload_path)),
                ('selfie_image', models.FileField(blank=True, null=True, upload_to=kyc_verification.models.kyc_upload_path)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('onfido', 'Onfido')], default='mock', max_length=30)),
                ('provider_applicant_id', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_document_id', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_selfie_id', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_check_id', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('id_uploaded', 'ID Uploaded'), ('selfie_uploaded', 'Selfie Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to='loan_applications.loanapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
