# Generated by Django 6.0.4 on 2026-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('onfido', 'Onfido'), ('complianceassist', 'ComplianceAssist')], default='mock', max_length=30),
        ),
    ]
