"""
Django settings for metamec project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from decouple import config
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "daphne",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'authentication',
    'rest_framework_simplejwt.token_blacklist',

    'loan_management',
    'loan_applications',
    'loan_documents',
    'admin_review',
    'kyc_verification',
    'loan_agreements',
    "channels",
    "support_chat",
    "user_notifications",
    "referrals",

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'metamec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'metamec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

AUTH_USER_MODEL = 'authentication.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=3000),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

OTP_EXPIRE_MINUTES = 50
OTP_MAX_ATTEMPTS = 100
OTP_MAX_RESEND = 40
PASSWORD_RESET_TOKEN_EXPIRE_MINUTES = 100


KYC_PROVIDER = config("KYC_PROVIDER", default="mock")
ONFIDO_API_TOKEN = config("ONFIDO_API_TOKEN", default="")
ONFIDO_WEBHOOK_SECRET = config("ONFIDO_WEBHOOK_SECRET", default="")


SITE_BASE_URL = config("SITE_BASE_URL", default="http://127.0.0.1:8010")


ASGI_APPLICATION = "metamec.asgi.application"

CHAT_USE_REDIS = config("CHAT_USE_REDIS", default=False, cast=bool)
REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/0")

if CHAT_USE_REDIS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

# REFERRAL_FRONTEND_BASE_URL = "https://loansphere.app/ref"
REFERRAL_FRONTEND_BASE_URL = "/api/auth/signup/ref"


COMPLIANCE_ASSIST_CLIENT_ID = config("COMPLIANCE_ASSIST_CLIENT_ID", default="")
COMPLIANCE_ASSIST_CLIENT_SECRET = config("COMPLIANCE_ASSIST_CLIENT_SECRET", default="")
COMPLIANCE_ASSIST_REQUEST_TYPE = config("COMPLIANCE_ASSIST_REQUEST_TYPE", default="AGP")
COMPLIANCE_ASSIST_AUTH_URL = config(
    "COMPLIANCE_ASSIST_AUTH_URL",
    default="https://auth-u.complianceassist.co.uk/oauth2/token",
)
COMPLIANCE_ASSIST_BASE_URL = config(
    "COMPLIANCE_ASSIST_BASE_URL",
    default="https://web-u.complianceassist.co.uk/api/v2_0",
).rstrip("/")


COMPLIANCE_ASSIST_WRITE_SCOPE = config(
    "COMPLIANCE_ASSIST_WRITE_SCOPE",
    default="uat/requests.write",
)

COMPLIANCE_ASSIST_READ_SCOPE = config(
    "COMPLIANCE_ASSIST_READ_SCOPE",
    default="uat/requests.read",
)
COMPLIANCE_ASSIST_SCOPE = config("COMPLIANCE_ASSIST_SCOPE", default="uat/requests.write")
COMPLIANCE_ASSIST_TIMEOUT = config("COMPLIANCE_ASSIST_TIMEOUT", default=30, cast=int)