# Generated by Django 6.0.4 on 2026-06-26 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application_received', 'Application Received'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('document_required', 'Document Required'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('chat_message', 'Chat Message'), ('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('e_sign_pending', 'E-sign Pending'), ('e_sign_completed', 'E-sign Completed'), ('co_applicant_invite', 'Co-applicant Invite'), ('payment_reminder', 'Payment Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('action_screen', models.CharField(blank=True, max_length=100, null=True)),
                ('action_api', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_ccfe25_idx'), models.Index(fields=['user', 'notification_type'], name='user_notifi_user_id_7c3d27_idx'), models.Index(fields=['user', 'created_at'], name='user_notifi_user_id_402a59_idx'), models.Index(fields=['notification_type'], name='user_notifi_notific_8ac0a0_idx')],
            },
        ),
    ]
