# Generated by Django 6.0.4 on 2026-06-24 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loan_term', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mortgage_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mortgage_lender', models.CharField(blank=True, max_length=180, null=True)),
                ('term_remaining', models.CharField(blank=True, max_length=80, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('other', 'Other')], max_length=30, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('has_ccj', models.BooleanField(blank=True, null=True)),
                ('has_defaults', models.BooleanField(blank=True, null=True)),
                ('has_active_dmp', models.BooleanField(blank=True, null=True)),
                ('has_active_iva', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_documents', 'Pending Documents'), ('kyc_required', 'KYC Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loan_management.loantype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
