# Generated by Django 6.0.4 on 2026-06-24 06:01

import django.db.models.deletion
import loan_documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport_driving_license', 'Passport / Driving License'), ('recent_photograph', 'Recent Photograph'), ('payslips_3_months', 'Last 3 Months Payslips'), ('latest_tax_return', 'Latest Tax Return'), ('bank_statement', 'Bank Statement')], max_length=80)),
                ('file', models.FileField(upload_to=loan_documents.models.loan_document_upload_path)),
                ('original_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='uploaded', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loan_applications.loanapplication')),
            ],
            options={
                'ordering': ['uploaded_at'],
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
