# Generated by Django 6.0.4 on 2026-07-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_last_login_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('support_staff', 'Support Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
