# Generated by Django 6.0.4 on 2026-06-26 03:17

import django.db.models.deletion
import support_chat.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_applications', '0001_initial'),
        ('support_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(default='Senior Loan Advisor', max_length=150)),
                ('speciality', models.CharField(default='Homeowner Loans', max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=312)),
                ('avatar', models.FileField(blank=True, null=True, upload_to=support_chat.models.support_agent_avatar_path)),
                ('available_call_types', models.JSONField(default=support_chat.models.default_support_call_types)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='support_chat.supportagent')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['agent', 'weekday', 'is_active'], name='support_cha_agent_i_84f80d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('live_chat', 'Live Chat')], max_length=30)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=30)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='support_chat.supportagent')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_appointments', to='loan_applications.loanapplication')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'start_time'],
                'indexes': [models.Index(fields=['customer', 'appointment_date'], name='support_cha_custome_8ed5c3_idx'), models.Index(fields=['agent', 'appointment_date', 'start_time'], name='support_cha_agent_i_f58c50_idx'), models.Index(fields=['status'], name='support_cha_status_0ec2af_idx')],
            },
        ),
    ]
