# Generated by Django 6.0.4 on 2026-08-18 03:59

import django.db.models.deletion
import support_chat.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0002_supportagent_agentavailability_supportappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTemplateFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_template_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='support_chat.chattemplatefolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility')], max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1024)),
                ('header_type', models.CharField(blank=True, choices=[('headline', 'Headline'), ('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], max_length=20, null=True)),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('header_file', models.FileField(blank=True, null=True, upload_to=support_chat.models.chat_template_attachment_path)),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_templates', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='support_chat.chattemplatefolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
